name: w0waMP
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip>=19.0
  - pip:
    - astropy>=4.0
    #- fast-pt>=3.1
    - jupyter>=1.0
    - cython
    - matplotlib>=3.1
    - numpy>=1.2
    - scipy>=1.7
    - getdist>=1.1.3
    - pyyaml
    - joblib
    - seaborn
    - openpyxl
    - gitpython
#    - pytest>=6.2
#    - pytest-cov>=2.10
#    - pytest-pycodestyle>=2.2.0
#    - pytest-pydocstyle>=2.2.0
